version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directories:
      - "/terraform/blog"
      - "/terraform/bootstrap"
      - "/terraform/lp"
      - "/terraform/maya"
      - "/terraform/news"
      - "/terraform/sabedoria"
      - "/terraform/wooka"
    schedule:
      interval: "daily"
