version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/blog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/bootstrap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/lp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/maya"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/news"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/sabedoria"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/wooka"
    schedule:
      interval: "weekly"
