CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY,
  content TEXT,
  link_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(link_id) REFERENCES links(id) ON DELETE CASCADE
);
