variable "aiven_cloud_name" {
  type    = string
  default = "do-nyc"
}

variable "aiven_maintenance_window_dow" {
  type    = string
  default = "tuesday"
}

variable "aiven_maintenance_window_time" {
  type    = string
  default = "10:00:00"
}

variable "aiven_plan" {
  type    = string
  default = "free-1-5gb"
}

variable "aiven_pg_version" {
  type    = number
  default = 14
}

variable "aiven_project_name" {
  type = string
}

variable "aiven_termination_protection" {
  type    = bool
  default = false
}

variable "b2_default_region" {
  type        = string
  default     = "us-east-005"
  description = "All bucket are created in this region"
}

variable "cloudflare_api_token" {
  type        = string
  description = "Token with permissions defined in workspace to deploy dns, pages"
}

variable "default_ttl" {
  type    = string
  default = 3600
}

variable "domain" {
  type        = string
  description = "Domain used in organization"
}

variable "email" {
  type        = string
  description = "Email used in account"
}

variable "environment" {
  type        = string
  description = "Environment used in organization"
}

variable "gcp_google_credentials" {
  type = string
}

variable "gcp_project_id" {
  type = string
}

variable "gcp_region" {
  type = string
}

variable "github_app_installation_id" {
  type        = string
  description = "This ID not is the ID in URL is internal TFE ID, needs use data"
}

variable "github_blog_repo" {
  type        = string
  default     = "blog"
  description = "Name of repostory with blog code"
}

variable "github_infra_repo" {
  type        = string
  description = "Name of repository that host project with Terraform files"
}

variable "github_lp_repo" {
  type        = string
  default     = "lp"
  description = "Name of repostory with landing pages and promotions"
}

variable "github_maps_repo" {
  type        = string
  default     = "maps"
  description = "Name of repostory with maps frontend application"
}

variable "github_news_repo" {
  type        = string
  default     = "news"
  description = "Name of repostory with news generated by osmosfeed"
}

variable "github_user" {
  type        = string
  description = "Username or organization slug"
}

variable "github_token" {
  type        = string
  description = "Token to insert vars in action and insert webhooks"
}

variable "github_verification_secret" {
  type        = string
  description = "Secret used to verify webhooks"
}

variable "mailgun_api_key" {
  type        = string
  description = "Authentication token generated to Mailgun"
}

variable "sentry_auth_token" {
  type        = string
  description = "Authentication token generated to Sentry"
}

variable "tfe_personal_token" {
  type        = string
  description = "Personal token, because organization token dont can used"
}

variable "tfe_verification_secret" {
  type        = string
  description = "Secret used to verify webhooks"
}

variable "wooka_bot_admins" {
  type = string
}

variable "wooka_bot_alt_prefixes" {
  type = string
}

variable "wooka_zulip_email" {
  type = string
}

variable "wooka_zulip_key" {
  type = string
}

variable "wooka_zulip_site" {
  type = string
}

variable "zulip_webhook_github" {
  type        = string
  description = "Webhook URL to Zulip integration"
}