# fly.toml app configuration file generated for droposhado-wooka on 2024-12-03T11:06:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'droposhado-wooka'
primary_region = 'iad'

[build]
  image = 'droposhado/wooka:latest'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
