name: push terraform lp

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-lp.yml'
      - 'terraform/lp/**'

  workflow_dispatch:

jobs:
  terraform-lp:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/lp'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
