name: push terraform furgao

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-furgao.yml'
      - 'terraform/furgao/**'

  workflow_dispatch:

jobs:
  terraform-furgao:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/furgao'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
