name: push terraform gotify

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-gotify.yml'
      - 'terraform/gotify/**'

  workflow_dispatch:

jobs:
  terraform-gotify:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/gotify'
    secrets:
      gcs_bucket: ${{ secrets.GCS_BUCKET }}
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}

