name: push terraform go

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-go.yml'
      - 'terraform/go/**'

  workflow_dispatch:

jobs:
  terraform-go:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/go'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
