name: push terraform maps

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-maps.yml'
      - 'terraform/maps/**'

  workflow_dispatch:

jobs:
  terraform-maps:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/maps'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
