name: push terraform sabedoria

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-sabedoria.yml'
      - 'terraform/sabedoria/**'

  workflow_dispatch:

jobs:
  terraform-sabedoria:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/sabedoria'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
