name: push terraform news

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-news.yml'
      - 'terraform/news/**'

  workflow_dispatch:

jobs:
  terraform-news:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/news'
    secrets:
      gcs_bucket: ${{ secrets.GCS_BUCKET }}
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}

