name: push terraform wooka

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-wooka.yml'
      - 'terraform/wooka/**'

  workflow_dispatch:

jobs:
  terraform-wooka:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/wooka'
    secrets:
      insifical_token: ${{ secrets.INFISICAL_TOKEN }}
