name: push terraform correnteza

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-correnteza.yml'
      - 'terraform/correnteza/**'

  workflow_dispatch:

jobs:
  terraform-correnteza:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/correnteza'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
