name: push terraform blog

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-blog.yml'
      - 'terraform/blog/**'

  workflow_dispatch:

jobs:
  terraform-blog:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/blog'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
