name: push terraform bootstrap

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-workflow.yml'
      - '.github/workflows/push-terraform-bootstrap.yml'
      - 'terraform/bootstrap/**'

  workflow_dispatch:

jobs:
  terraform-bootstrap:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      path: 'terraform/bootstrap'
    secrets:
      infisical_token: ${{ secrets.INFISICAL_TOKEN }}
