name: scheduler bem-te-vi alert
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/scheduler-bem-te-vi-alert.yml'

  schedule:
    - cron: '00 06 * * *'

  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - uses: droposhado/bem-te-vi-action@main
        with:
          btv_debug: ${{ secrets.BTV_DEBUG }}
          webdav_server: ${{ secrets.WEBDAV_SERVER }}
          webdav_username: ${{ secrets.WEBDAV_USERNAME }}
          webdav_password: ${{ secrets.WEBDAV_PASSWORD }}
          webdav_addressbook: ${{ secrets.WEBDAV_ADRESSBOOK }}
          webhook_url: ${{ secrets.BEMTEVI_WEBHOOK_URL }}
          date_layout: ${{ secrets.DATE_LAYOUT }}
          bot_name: ${{ secrets.BOT_NAME }}
          icon_url: ${{ secrets.ICON_URL }}

      # - name: push to kuma - success
      #   if: success()
      #   run: curl "${{ secrets.BEMTEVI_UPTIME_PUSH_URL }}?status=up&msg=OK&ping="

      # - name: push to kuma - failure
      #   if: failure()
      #   run: curl "${{ secrets.BEMTEVI_UPTIME_PUSH_URL }}?status=down&msg=OK&ping="
