name: scheduler mirror multi

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: mirror-repository
        uses: droposhado/mirror-action@v0.6.0
        with:
          REMOTE: git@github.com:droposhado/infra.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.INFRA_MIRROR_SSH_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          DEBUG: "true"

      - name: push to kuma - success
        if: ${{ success() }}
        run: curl "${{ secrets.INFRA_UPTIME_PUSH_URL }}?status=up&msg=OK&ping="

      - name: push to kuma - failure or cancelled
        if: ${{ always() && (failure() || cancelled()) }}
        run: curl "${{ secrets.INFRA_UPTIME_PUSH_URL }}?status=down&msg=OK&ping="
