name: terraform droposhado[secrets] push

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-droposhado.org-secrets-push.yml'
      - 'terraform/secrets/**'

  workflow_dispatch:

jobs:
  checks:
    uses: droposhado/workflows/.github/workflows/terraform-best-practices.yml@main
    with:
      dir: 'terraform/secrets'
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}

  apply:
    needs:
      - checks
    uses: droposhado/workflows/.github/workflows/terraform-apply.yml@main
    with:
      dir: 'terraform/droposhado/secrets'
      organization: 'droposhado-org'
      workspace: 'secrets'
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
